// AUTOGENERATED FROM PICO_CONFIG_HEADER_FILES and then PICO_<PLATFORM>_CONFIG_HEADER_FILES
// DO NOT EDIT!

// based on PICO_CONFIG_HEADER_FILES:
#include "..\..\..\..\..\..\..\SDK\src\boards\include\boards\pico.h"

// based on PICO_RP2040_CONFIG_HEADER_FILES:
#include "..\..\..\..\..\..\..\SDK\src\rp2_common\cmsis\include\cmsis\rename_exceptions.h"
